// GitHub Pages runs Jekyll unless told otherwise, and Jekyll drops _next/.
// PRD §12: `.nojekyll` must exist in the output root.
//
// Also generates the service worker. PRD §11 asks for the site to be fully
// offline after first load, which browser HTTP caching alone does not give:
// a reload with no network fails without a worker serving from a cache.
import { readdir, readFile, stat, writeFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { join, relative, sep } from 'node:path'

const OUT = join(process.cwd(), 'out')
const BASE_PATH = '/myers-visualizer'
// Must match DEFAULT_LOCALE in lib/i18n/locales.ts. Only used to pick the
// offline navigation shell, so a stale value degrades the offline fallback
// rather than breaking the site.
const DEFAULT_LOCALE = 'en'

await writeFile(join(OUT, '.nojekyll'), '')
console.log('postbuild: wrote out/.nojekyll')

/**
 * `<html lang>` per locale.
 *
 * The App Router allows exactly one layout to render <html>, and that is the
 * root one, which is shared by both locales and has no params. So the lang
 * attribute was hard-coded to English and patched after hydration by a client
 * component — which meant every crawler, and every screen reader reading the
 * static document, saw Indonesian pages declared as English.
 *
 * Rewriting it here fixes it in the shipped bytes instead. Deterministic, and
 * asserted by tests/ui/seo.test.ts against the built output.
 */
async function setLangAttributes(locales) {
  let changed = 0
  for (const path of await walk(OUT)) {
    if (!path.endsWith('.html')) continue
    const rel = relative(OUT, path).split(sep).join('/')
    const locale = locales.find((code) => rel === `${code}/index.html` || rel.startsWith(`${code}/`))
    if (locale === undefined || locale === DEFAULT_LOCALE) continue
    const html = await readFile(path, 'utf8')
    const patched = html.replace('<html lang="en"', `<html lang="${locale}"`)
    if (patched === html) continue
    await writeFile(path, patched)
    changed++
  }
  return changed
}

async function walk(dir) {
  const found = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name)
    if (entry.isDirectory()) found.push(...(await walk(path)))
    else found.push(path)
  }
  return found
}

const relabelled = await setLangAttributes(['en', 'id'])
console.log(`postbuild: set <html lang> on ${relabelled} non-default-locale pages`)

const files = await walk(OUT)
const assets = []

for (const path of files) {
  const rel = relative(OUT, path).split(sep).join('/')
  if (rel === '.nojekyll' || rel === 'sw.js' || rel.endsWith('.map')) continue
  // The social card is fetched by crawlers, never by the app. Precaching it
  // would spend 40 KB of a visitor's offline budget on an image they will
  // never see.
  if (rel === 'brand/og.png') continue
  // A directory's index.html is requested as the directory URL, so that is
  // the form the cache has to be keyed by.
  if (rel.endsWith('/index.html')) assets.push(`${BASE_PATH}/${rel.slice(0, -'index.html'.length)}`)
  else if (rel === 'index.html') assets.push(`${BASE_PATH}/`)
  else assets.push(`${BASE_PATH}/${rel}`)
}
assets.sort()

// Version derived from the content, not from a clock, so an unchanged build
// produces an unchanged worker and browsers do not churn their caches.
const fingerprint = createHash('sha256')
for (const path of files.sort()) {
  fingerprint.update(relative(OUT, path))
  fingerprint.update(String((await stat(path)).size))
}
const version = fingerprint.digest('hex').slice(0, 12)

const sw = `/*
 * Myers Visualizer service worker — generated by scripts/postbuild.mjs. Do not edit.
 *
 * Everything here is immutable: Next fingerprints its assets, and the HTML is
 * re-precached whenever the build changes because CACHE carries a hash of the
 * output. So the strategy is cache-first, with the network only as a fallback
 * for anything missed.
 */
const CACHE = 'myers-visualizer-${version}'
const PRECACHE = ${JSON.stringify(assets, null, 2)}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      // One failed asset must not fail the whole install, or a single 404
      // leaves the site with no offline support at all.
      .then((cache) => Promise.allSettled(PRECACHE.map((url) => cache.add(url))))
      .then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return

  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return
  if (!url.pathname.startsWith('${BASE_PATH}')) return

  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then((hit) => {
      if (hit !== undefined) return hit
      return fetch(request).catch(() => {
        // Offline and unseen. A navigation still gets a real page rather than
        // the browser's error, so the app shell loads and can explain itself.
        if (request.mode === 'navigate') {
          return caches.match('${BASE_PATH}/${DEFAULT_LOCALE}/graf/', { ignoreSearch: true }).then(
            (shell) => shell ?? Response.error(),
          )
        }
        return Response.error()
      })
    }),
  )
})
`

await writeFile(join(OUT, 'sw.js'), sw)
console.log(`postbuild: wrote out/sw.js — ${assets.length} assets, cache myers-visualizer-${version}`)
